services:
  - type: web
    name: verilog-chatbot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.app:app"
    envVars:
      PYTHON_VERSION: 3.10
